SERVER_OK = 0
SERVER_ERROR = 1
DATABASE_ERROR = 2
OPERATION_NOT_SUPPORTED = 3
NO_PERMISSION = 4

SERVER_OK_MESSAGE = ''
DATABASE_ERROR_MESSAGE = 'Database Error occurred'
OPERATION_NOT_SUPPORTED_MESSAGE = 'Operation not supported'
NO_PERMISSION_MESSAGE = 'Insufficient permission'
SERVER_ERROR_MESSAGE = 'Server Error'
